cluster:
  name: playsay-postgres
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-system-trixie
  database: playsay
  owner: playsay_app
  storage:
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 384Mi
  postgresql:
    parameters:
      shared_buffers: 64MB
      max_connections: "50"
  managed:
    roles:
      - name: keyboard_app
        ensure: present
        login: true
        passwordSecret:
          name: playsay-postgres-keyboard

databases:
  - name: keyboard
    owner: keyboard_app
    ensure: present
    reclaimPolicy: retain
