image:
  repository: ghcr.io/mednov-ai/playsay-api-gateway
  tag: "ce0c24aa125ae477013c5a553d5fc3cff33b1b48"
imagePullSecrets:
  - name: ghcr-pull-secret
ingress:
  enabled: false
  host: hello.dev.example.com
