image:
  repository: ghcr.io/mednov-ai/playsay-api-gateway
  tag: "0.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

replicaCount: 1

service:
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: hello.dev.playsay.local
  tlsSecretName: hello-world-tls
  clusterIssuer: letsencrypt-http01

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
