image:
  repository: ghcr.io/mednov-ai/playsay-api-gateway
  tag: "7bbf33093fd9f88d47545e219066bf9f294d09c9"
imagePullSecrets:
  - name: ghcr-pull-secret
ingress:
  enabled: false
  host: hello.dev.example.com
