image:
  repository: ghcr.io/mednov-ai/playsay-payment-service
  tag: "payment-dev-33"
  digest: sha256:9819100cdd37b6e50864d78b103c51e625ede7262e9b14fe9904af9807100a57
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: payment-dev-33
  number: "33"
  branch: develop
  branchLabel: payment-dev
  commit: af467f645201c9abe7d501bafcfc8f8fa0ef3573
  commitShort: "af467f645201"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
paymentService:
  existingSecret: playsay-payment
  publicBaseUrl: https://dev.online.honey.school
  provider: yookassa
  yookassa:
    apiUrl: https://api.yookassa.ru/v3
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=15 -XX:MaxRAMPercentage=45 -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=32m -XX:ActiveProcessorCount=1 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 320Mi
