image:
  repository: ghcr.io/mednov-ai/playsay-payment-service
  tag: "payment-release-01.004.13-24"
  digest: "sha256:52dc8da6ee2bcd732713a6c5d9a0fecb4d759dd3144e4b9647abc9ae074a51b9"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: payment-release-01.004.13-24
  number: "24"
  branch: release/01.004.13
  branchLabel: payment-release-01.004.13
  commit: 9812e78400c2b8747537f7fe97e43bfffaaaef29
  commitShort: "9812e78400c2"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
paymentService:
  existingSecret: playsay-payment
  publicBaseUrl: https://online.honey.school
  provider: yookassa
  yookassa:
    apiUrl: https://api.yookassa.ru/v3
runtime:
  javaToolOptions: "-Xms96m -Xmx192m -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=32m -XX:ActiveProcessorCount=1 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
