image:
  repository: ghcr.io/mednov-ai/playsay-payment-service
  tag: "dev-192"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: dev-192
  number: "192"
  branch: develop
  branchLabel: dev
  commit: 948c7003eb171aad706dcdbe45fb9a85a29b2ee6
  commitShort: "948c7003eb17"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
paymentService:
  existingSecret: playsay-payment
  publicBaseUrl: https://online.play-and-say.ru
  provider: yookassa
  yookassa:
    apiUrl: https://api.yookassa.ru/v3
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=75 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi
