image:
  repository: ghcr.io/mednov-ai/playsay-payment-service
  tag: "payment-dev-20"
  digest: sha256:910cd7b67cb11c77f185e88484185e6a6ad9c82c5d8b4a300ba573ca0749e555
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: payment-dev-20
  number: "20"
  branch: develop
  branchLabel: payment-dev
  commit: 151a7911ed16dfee9b6ebc87a9855967208a53be
  commitShort: "151a7911ed16"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
paymentService:
  existingSecret: playsay-payment
  publicBaseUrl: https://dev.online.honey.school
  provider: yookassa
  yookassa:
    apiUrl: https://api.yookassa.ru/v3
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=15 -XX:MaxRAMPercentage=45 -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=32m -XX:ActiveProcessorCount=1 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 320Mi
