image:
  repository: ghcr.io/mednov-ai/playsay-payment-service
  tag: "payment-release-01.004.13-25"
  digest: "sha256:7331550df9ae2f64dcf30afc20880d3e22d1b97dace7f5d06f9c0c9e43b562c1"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: payment-release-01.004.13-25
  number: "25"
  branch: release/01.004.13
  branchLabel: payment-release-01.004.13
  commit: b15c57a619dddd0e7172b7c9b7aea682f7d0e6f0
  commitShort: "b15c57a619dd"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
paymentService:
  existingSecret: playsay-payment
  publicBaseUrl: https://online.honey.school
  provider: yookassa
  yookassa:
    apiUrl: https://api.yookassa.ru/v3
runtime:
  javaToolOptions: "-Xms96m -Xmx192m -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=32m -XX:ActiveProcessorCount=1 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
