image:
  repository: ghcr.io/mednov-ai/playsay-payment-service
  tag: "payment-release-01.007.03-28"
  digest: "sha256:450b7c5e988621b100ec8706197653f61dc9b794399349716d334250e779ad38"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: payment-release-01.007.03-28
  number: "28"
  branch: release/01.007.03
  branchLabel: payment-release-01.007.03
  commit: ea2b1c38c2948523990cd0d4c036aeec63625449
  commitShort: "ea2b1c38c294"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
paymentService:
  existingSecret: playsay-payment
  publicBaseUrl: https://online.honey.school
  provider: yookassa
  yookassa:
    apiUrl: https://api.yookassa.ru/v3
runtime:
  javaToolOptions: "-Xms96m -Xmx192m -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=32m -XX:ActiveProcessorCount=1 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
