apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playsay-dev-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mednov-ai/playsay-infra.git
    targetRevision: develop
    path: argocd-apps/dev/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
