apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playsay-prod-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mednov-ai/playsay-infra.git
    targetRevision: release/01.006.14
    path: argocd-apps/prod/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
