image:
  repository: ghcr.io/mednov-ai/playsay-media-service
  tag: "dev-181"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: dev-181
  number: "181"
  branch: develop
  branchLabel: dev
  commit: c49454cbb69f75d1fd0806ccb3ac1444757e163c
  commitShort: "c49454cbb69f"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
mediaService:
  existingSecret: playsay-media
  sessionTtlSeconds: "900"
  maxUpstreamRangeBytes: "1048576"
  maxThumbnailBytes: "5242880"
  ytdlpPath: /usr/local/bin/yt-dlp
storage:
  provider: s3
  s3:
    endpoint: http://minio.storage.svc.cluster.local:9000
    region: us-east-1
    bucket: playsay-material-assets
    existingSecret: playsay-object-storage
    pathStyleAccess: "true"
    createBucket: "true"
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=75 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi
