apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - service-accounts.yaml
  - workflow-rbac.yaml
  - backup-rbac.yaml
  - migration-rbac.yaml
  - argocd-rbac.yaml
  - prod-liquibase-runner.yaml
  - migration-admission.yaml
  - workflow-template-promotion.yaml
  - workflow-template-rollback.yaml
  - release-tools
