configs:
  cm:
    url: https://argocd.ops.honey.school
    oidc.config: |
      name: Play&Say Workforce
      issuer: https://ops.honey.school/keycloak/realms/workforce
      clientID: ops-argocd-prod
      clientSecret: $oidc.workforce.clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
  params:
    server.insecure: true
    server.basehref: /
    server.rootpath: /
  rbac:
    policy.default: role:workforce-deny
    scopes: "[groups]"
    policy.csv: |
      p, role:workforce-deny, applications, get, __no_access__/*, allow
      p, role:workforce-readonly, applications, get, */*, allow
      p, role:workforce-readonly, projects, get, *, allow
      p, role:workforce-readonly, repositories, get, *, allow
      p, role:workforce-readonly, clusters, get, *, allow
      p, role:workforce-readonly, logs, get, */*, allow
      g, developers, role:workforce-readonly
      g, release-operators, role:workforce-readonly
      g, platform-admins, role:workforce-readonly

server:
  service:
    type: NodePort
    nodePortHttp: 32080
  ingress:
    enabled: false
