image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-app
  tag: "key-frontend-release-1.001.07-69"
  digest: "sha256:7eedcb455b1fcbd5eafc0c19ada34141d7819dccb0eb5e939a4c840626fb5c18"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-frontend-release-1.001.07-69
  number: "69"
  branch: release/1.001.07
  branchLabel: key-frontend-release-1.001.07
  commit: a171a7eda31f9faf8252cc5081a8435f3a12012e
  commitShort: a171a7eda31f
service:
  type: NodePort
  nodePort: 32087
