image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-app
  tag: "key-frontend-dev-63"
  digest: sha256:544014bf6989c48d3dc0fd96e1ab7e476f9b70d149248986c29cdf6732aebe77
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-frontend-dev-63
  number: "63"
  branch: develop
  branchLabel: key-frontend-dev
  commit: 9ef3dff9d77bcc5f4449bd031fb3cb33000ced57
  commitShort: 9ef3dff9d77b
service:
  type: NodePort
  nodePort: 32087
