image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-app
  tag: "key-frontend-dev-90"
  digest: sha256:300e34604808f3b08c550ba668602257e35405fade5d295de922735538915885
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-frontend-dev-90
  number: "90"
  branch: develop
  branchLabel: key-frontend-dev
  commit: d9ecf194a520c1041a8513a84373253ac640a482
  commitShort: d9ecf194a520
service:
  type: NodePort
  nodePort: 32087
