image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-app
  tag: "key-frontend-release-1.001.09-84"
  digest: "sha256:bf83fe7a419ec14044ccc9c86999370e30669f1cf18f0891b4af8ad2eef178de"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-frontend-release-1.001.09-84
  number: "84"
  branch: release/1.001.09
  branchLabel: key-frontend-release-1.001.09
  commit: 69c27d0dc9bfbf7b201ab8088b551ce6be29c2af
  commitShort: 69c27d0dc9bf
service:
  type: NodePort
  nodePort: 32087
