image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-app
  tag: "key-frontend-release-01.004.12-92"
  digest: "sha256:9f996148b493bdc6d154a856bef390ebfec880c66b2c1ce99c3e657aa25fa0c3"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-frontend-release-01.004.12-92
  number: "92"
  branch: release/01.004.12
  branchLabel: key-frontend-release-01.004.12
  commit: d18830a1b4197cd0c8d2712718a415aae074193c
  commitShort: d18830a1b419
service:
  type: NodePort
  nodePort: 32087
