---
timezone: Europe/Moscow
admin_user: playsay
ssh_port: 22

manage_ssh_hardening: false
manage_ufw: false
install_docker: false
swap_file_path: /swapfile
swap_file_size: 2G

ufw_allow_k3s_api_public: false
ufw_extra_tcp_ports:
  - 80
  - 443

coturn_realm: online.play-and-say.ru
coturn_external_ip: 89.124.113.223
coturn_listening_port: 3478
coturn_min_port: 49160
coturn_max_port: 49200

k3s_version: v1.35.5+k3s1
k3s_cluster_cidr: 10.42.0.0/16
k3s_service_cidr: 10.43.0.0/16
k3s_disable_components:
  - traefik
  - servicelb
k3s_node_taints: []

node_exporter_enabled: true
