feature: {enabled: true}
auth:
  issuerUri: https://dev.ops.honey.school/keycloak/realms/playsay
  jwkSetUri: https://dev.ops.honey.school/keycloak/realms/playsay/protocol/openid-connect/certs
storage: {endpoint: 'http://minio.playsay-dev.svc.cluster.local:9000'}
analysis: {provider: stub}
runtime: {javaToolOptions: "-XX:InitialRAMPercentage=20 -XX:MaxRAMPercentage=55 -XX:ActiveProcessorCount=1"}
image:
  tag: worksheet-import-dev-3
  digest: sha256:46417db31ad7f321624941583323afccf9f1b362b4bed65b31908280e5a4613c
build:
  name: worksheet-import-dev-3
  number: "3"
  branch: develop
  branchLabel: worksheet-import-dev
  commit: 30422fbd10b2b2bff7eed6d966ee65805b71dfec
  commitShort: 30422fbd10b2
