feature: {enabled: true}
imagePullSecrets:
  - name: ghcr-pull-secret
auth:
  issuerUri: https://dev.ops.honey.school/keycloak/realms/playsay
  jwkSetUri: https://dev.ops.honey.school/keycloak/realms/playsay/protocol/openid-connect/certs
storage: {endpoint: 'http://minio.storage.svc.cluster.local:9000'}
analysis: {provider: stub}
runtime: {javaToolOptions: "-XX:InitialRAMPercentage=20 -XX:MaxRAMPercentage=55 -XX:ActiveProcessorCount=1"}
image:
  tag: worksheet-import-dev-5
  digest: sha256:6d18d093565765087b8a27542a2646119a512e4f20f91124b4f95a94b58fb782
build:
  name: worksheet-import-dev-5
  number: "5"
  branch: develop
  branchLabel: worksheet-import-dev
  commit: 91f815a131df91a6def7c4466d0b5a231969c91a
  commitShort: 91f815a131df
