feature: {enabled: false}
auth:
  issuerUri: https://ops.honey.school/keycloak/realms/playsay
  jwkSetUri: https://ops.honey.school/keycloak/realms/playsay/protocol/openid-connect/certs
storage: {endpoint: 'http://minio.playsay-prod.svc.cluster.local:9000'}
analysis: {provider: stub}
image:
  tag: worksheet-import-release-01.004.13-15
  digest: sha256:c5e2b5df6d12e7d9c0f8443aa55af4663a3309d10e31ff53d834fbecd7ed2966
build:
  name: worksheet-import-release-01.004.13-15
  number: "15"
  branch: release/01.004.13
  branchLabel: worksheet-import-release-01.004.13
  commit: b15c57a619dddd0e7172b7c9b7aea682f7d0e6f0
  commitShort: b15c57a619dd
