feature: {enabled: true}
imagePullSecrets:
  - name: ghcr-pull-secret
auth:
  issuerUri: https://ops.honey.school/keycloak/realms/playsay
  jwkSetUri: https://ops.honey.school/keycloak/realms/playsay/protocol/openid-connect/certs
storage: {endpoint: 'http://minio.storage.svc.cluster.local:9000'}
analysis: {provider: stub}
image:
  tag: worksheet-import-release-01.007.03-20
  digest: sha256:4867d84c1e9a83bc4d4dad2730af1c66cf996283ea56219b0b5f1e4b94817847
build:
  name: worksheet-import-release-01.007.03-20
  number: "20"
  branch: release/01.007.03
  branchLabel: worksheet-import-release-01.007.03
  commit: ea2b1c38c2948523990cd0d4c036aeec63625449
  commitShort: ea2b1c38c294
