feature: {enabled: false}
auth:
  issuerUri: https://ops.honey.school/keycloak/realms/playsay
  jwkSetUri: https://ops.honey.school/keycloak/realms/playsay/protocol/openid-connect/certs
storage: {endpoint: 'http://minio.playsay-prod.svc.cluster.local:9000'}
analysis: {provider: stub}
image:
  tag: worksheet-import-release-01.004.12-12
  digest: sha256:3c5abcb90095dd690d4bb4f10282a5142733f358911e00ac80de40760244e066
build:
  name: worksheet-import-release-01.004.12-12
  number: "12"
  branch: release/01.004.12
  branchLabel: worksheet-import-release-01.004.12
  commit: d18830a1b4197cd0c8d2712718a415aae074193c
  commitShort: d18830a1b419
