apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: keycloak
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: keycloak
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      nodePort: {{ .Values.keycloak.service.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: keycloak
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: keycloak
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
