apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-playsay-theme
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: playsay
data:
  theme.properties: |-
{{ .Files.Get "themes/playsay/login/theme.properties" | indent 4 }}
  template.ftl: |-
{{ tpl (.Files.Get "themes/playsay/login/template.ftl") . | indent 4 }}
  login.ftl: |-
{{ .Files.Get "themes/playsay/login/login.ftl" | indent 4 }}
  webauthn-register.ftl: |-
{{ .Files.Get "themes/playsay/login/webauthn-register.ftl" | indent 4 }}
  playsay-webauthn-register.js: |-
{{ .Files.Get "themes/playsay/login/resources/js/playsayWebAuthnRegister.js" | indent 4 }}
  playsay-passkey-login.js: |-
{{ .Files.Get "themes/playsay/login/resources/js/playsayPasskeyLogin.js" | indent 4 }}
  messages_en.properties: |-
{{ .Files.Get "themes/playsay/login/messages/messages_en.properties" | indent 4 }}
  messages_ru.properties: |-
{{ .Files.Get "themes/playsay/login/messages/messages_ru.properties" | indent 4 }}
  messages_de.properties: |-
{{ .Files.Get "themes/playsay/login/messages/messages_de.properties" | indent 4 }}
  messages_fr.properties: |-
{{ .Files.Get "themes/playsay/login/messages/messages_fr.properties" | indent 4 }}
  playsay-login.css: |-
{{ .Files.Get "themes/playsay/login/resources/css/playsay-login.css" | indent 4 }}
binaryData:
  honey-school-logo.svg: {{ .Files.Get "themes/playsay/login/resources/img/honey-school-logo.svg" | b64enc }}
  honey-school-logo-reverse.svg: {{ .Files.Get "themes/playsay/login/resources/img/honey-school-logo-reverse.svg" | b64enc }}
  favicon.svg: {{ .Files.Get "themes/playsay/login/resources/img/favicon.svg" | b64enc }}
  quicksand-latin-400.woff2: {{ .Files.Get "themes/playsay/login/resources/fonts/quicksand-latin-400.woff2" | b64enc }}
  quicksand-latin-500.woff2: {{ .Files.Get "themes/playsay/login/resources/fonts/quicksand-latin-500.woff2" | b64enc }}
  quicksand-latin-600.woff2: {{ .Files.Get "themes/playsay/login/resources/fonts/quicksand-latin-600.woff2" | b64enc }}
