apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mednov-ai/playsay-infra.git
    targetRevision: develop
    path: helm-charts/media-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: playsay-dev
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: media-service
      namespace: playsay-dev
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
