image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-service
  tag: "key-backend-users-2ef8964"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-backend-users-2ef8964
  number: "manual"
  branch: develop
  branchLabel: key-backend-users
  commit: 2ef89645d1880eb374c5c3263002342034110e98
  commitShort: 2ef89645d188
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-keyboard-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=75 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
