image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-service
  tag: "key-backend-release-01.004.13-43"
  digest: "sha256:df66d412fd06f6b84c9a18ffda61b377ecb4ef974522d1a93e67b88b39bc1294"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-backend-release-01.004.13-43
  number: "43"
  branch: release/01.004.13
  branchLabel: key-backend-release-01.004.13
  commit: b15c57a619dddd0e7172b7c9b7aea682f7d0e6f0
  commitShort: b15c57a619dd
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-keyboard-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
runtime:
  javaToolOptions: "-Xms256m -Xmx512m -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
vocabularyIntegration:
  baseUrl: http://vocabulary-service.playsay-prod.svc.cluster.local
resources:
  requests:
    cpu: 50m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
