image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-service
  tag: "key-backend-dev-45"
  digest: sha256:361941988b74dab932a6ca262b701b15fa6d6fd30e2d500cd7e6c7dbab04e7ce
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-backend-dev-45
  number: "45"
  branch: develop
  branchLabel: key-backend-dev
  commit: ea2b1c38c2948523990cd0d4c036aeec63625449
  commitShort: ea2b1c38c294
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
auth:
  issuerUri: https://dev.ops.honey.school/keycloak/realms/playsay
  jwkSetUri: http://keycloak.keycloak.svc.cluster.local/keycloak/realms/playsay/protocol/openid-connect/certs
database:
  existingSecret: playsay-keyboard-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=75 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
vocabularyIntegration:
  baseUrl: http://vocabulary-service.playsay-dev.svc.cluster.local
