image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-service
  tag: "key-backend-release-01.007.06-51"
  digest: "sha256:8b6f019642b26e734705082c569e2f5e36280212fe2adfaf35d3ccff1a1a7b19"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-backend-release-01.007.06-51
  number: "51"
  branch: release/01.007.06
  branchLabel: key-backend-release-01.007.06
  commit: a5ae66a15d1fed1f6d74adaca72a5d6ee272e3d7
  commitShort: a5ae66a15d1f
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-keyboard-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
runtime:
  javaToolOptions: "-Xms256m -Xmx512m -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
vocabularyIntegration:
  baseUrl: http://vocabulary-service.playsay-prod.svc.cluster.local
resources:
  requests:
    cpu: 50m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
