image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-service
  tag: "key-backend-dev-21"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-backend-dev-21
  number: "21"
  branch: develop
  branchLabel: key-backend-dev
  commit: dd5825128e5d326f26e6168fd0e5d2db3f751c5a
  commitShort: dd5825128e5d
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-keyboard-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=75 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
