image:
  repository: ghcr.io/mednov-ai/playsay-keyboard-service
  tag: "key-backend-release-01.007.05-50"
  digest: "sha256:8311fb3ca801ee747ad34e41651a5e88a5a1a4714c199f4465c69eae9ed0562a"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: key-backend-release-01.007.05-50
  number: "50"
  branch: release/01.007.05
  branchLabel: key-backend-release-01.007.05
  commit: af467f645201c9abe7d501bafcfc8f8fa0ef3573
  commitShort: af467f645201
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-keyboard-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
runtime:
  javaToolOptions: "-Xms256m -Xmx512m -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
vocabularyIntegration:
  baseUrl: http://vocabulary-service.playsay-prod.svc.cluster.local
resources:
  requests:
    cpu: 50m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
