image:
  repository: ghcr.io/mednov-ai/playsay-collaboration-service
  tag: "collab-release-01.006.05-40"
  digest: "sha256:42387a0361aad7dfe0f3b6f71878293af3da0aff482cf7d93826658782ae3506"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: collab-release-01.006.05-40
  number: "40"
  branch: release/01.006.05
  branchLabel: collab-release-01.006.05
  commit: 62e1a01cf4292002c8870e307480108f00954889
  commitShort: "62e1a01cf429"
service:
  type: NodePort
  nodePort: 32086
auth:
  keycloakJwksUrl: http://keycloak.keycloak.svc.cluster.local/keycloak/realms/playsay/protocol/openid-connect/certs
apiGateway:
  baseUrl: http://api-gateway.playsay-prod.svc.cluster.local
collaboration:
  existingSecret: playsay-collaboration
  snapshotIntervalMs: "10000"
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi
