image:
  repository: ghcr.io/mednov-ai/playsay-collaboration-service
  tag: "collab-release-01.004.13-36"
  digest: "sha256:4fdc8f6cdd211f7dc6d52a8cd6633463b6093131a07f20b3b6e1946ae84c50d0"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: collab-release-01.004.13-36
  number: "36"
  branch: release/01.004.13
  branchLabel: collab-release-01.004.13
  commit: 9812e78400c2b8747537f7fe97e43bfffaaaef29
  commitShort: "9812e78400c2"
service:
  type: NodePort
  nodePort: 32086
auth:
  keycloakJwksUrl: http://keycloak.keycloak.svc.cluster.local/keycloak/realms/playsay/protocol/openid-connect/certs
apiGateway:
  baseUrl: http://api-gateway.playsay-prod.svc.cluster.local
collaboration:
  existingSecret: playsay-collaboration
  snapshotIntervalMs: "10000"
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi
