image:
  repository: ghcr.io/mednov-ai/playsay-collaboration-service
  tag: "collab-dev-31"
  digest: sha256:f8c52b8cc00d6fc2beb4b4208794380bcce3671b766b9f8a4df5092dca0bef2a
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: collab-dev-31
  number: "31"
  branch: develop
  branchLabel: collab-dev
  commit: c524cd7f01086d01b363fbf9b3f5736d5c0485bb
  commitShort: "c524cd7f0108"
service:
  type: NodePort
  nodePort: 32086
apiGateway:
  baseUrl: http://api-gateway.playsay-dev.svc.cluster.local
collaboration:
  existingSecret: playsay-collaboration
  gameRealtimeMode: shadow
  snapshotIntervalMs: "10000"
