image:
  repository: ghcr.io/mednov-ai/playsay-collaboration-service
  tag: "dev-135"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: dev-135
  number: "135"
  branch: develop
  branchLabel: dev
  commit: 70c62955e908f3316aaad4691eb8c4b83a844c39
  commitShort: "70c62955e908"
service:
  type: NodePort
  nodePort: 32086
apiGateway:
  baseUrl: http://api-gateway.playsay-dev.svc.cluster.local
collaboration:
  existingSecret: playsay-collaboration
  snapshotIntervalMs: "10000"
