image:
  repository: ghcr.io/mednov-ai/playsay-collaboration-service
  tag: "collab-release-1.001.09-30"
  digest: "sha256:0ac8a461bba5a7845a8ccdb8102f87323f877fffd4b97829e4f6a2d9461a079e"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: collab-release-1.001.09-30
  number: "30"
  branch: release/1.001.09
  branchLabel: collab-release-1.001.09
  commit: 69c27d0dc9bfbf7b201ab8088b551ce6be29c2af
  commitShort: "69c27d0dc9bf"
service:
  type: NodePort
  nodePort: 32086
auth:
  keycloakJwksUrl: http://keycloak.keycloak.svc.cluster.local/keycloak/realms/playsay/protocol/openid-connect/certs
apiGateway:
  baseUrl: http://api-gateway.playsay-prod.svc.cluster.local
collaboration:
  existingSecret: playsay-collaboration
  snapshotIntervalMs: "10000"
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 768Mi
