image:
  repository: ghcr.io/mednov-ai/playsay-collaboration-service
  tag: "collab-dev-23"
  digest: sha256:7dd5e80364f56f552d1c21476efda73e175f1e943de99674598f114e5d9e92b8
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: collab-dev-23
  number: "23"
  branch: develop
  branchLabel: collab-dev
  commit: 13650a3c90fd219c8f54bc44b91dff5d01bf92b0
  commitShort: "13650a3c90fd"
service:
  type: NodePort
  nodePort: 32086
apiGateway:
  baseUrl: http://api-gateway.playsay-dev.svc.cluster.local
collaboration:
  existingSecret: playsay-collaboration
  snapshotIntervalMs: "10000"
