image:
  repository: ghcr.io/mednov-ai/playsay-web-app
  tag: "web-release-01.007.06-322"
  digest: "sha256:b8e14c788dd0c726f3dd746f52baa9ae80fe7a0e192cc36aa6fd02fc7a308f44"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: web-release-01.007.06-322
  number: "322"
  branch: release/01.007.06
  branchLabel: web-release-01.007.06
  commit: a5ae66a15d1fed1f6d74adaca72a5d6ee272e3d7
  commitShort: "a5ae66a15d1f"
service:
  type: NodePort
  nodePort: 32083
