image:
  repository: ghcr.io/mednov-ai/playsay-web-app
  tag: "web-dev-25"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: web-dev-25
  number: "25"
  branch: develop
  branchLabel: web-dev
  commit: d39475ad6c5de348204be6604cafac148754a8c3
  commitShort: "d39475ad6c5d"
service:
  type: NodePort
  nodePort: 32083
