apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  labels:
    app.kubernetes.io/name: app-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    playsay.io/component: app-postgres
spec:
  instances: {{ .Values.cluster.instances }}
  imageName: {{ .Values.cluster.imageName | quote }}
  bootstrap:
    initdb:
      database: {{ .Values.cluster.database | quote }}
      owner: {{ .Values.cluster.owner | quote }}
  storage:
    size: {{ .Values.cluster.storage.size | quote }}
  resources:
    requests:
      cpu: {{ .Values.cluster.resources.requests.cpu | quote }}
      memory: {{ .Values.cluster.resources.requests.memory | quote }}
    limits:
      cpu: {{ .Values.cluster.resources.limits.cpu | quote }}
      memory: {{ .Values.cluster.resources.limits.memory | quote }}
  postgresql:
    parameters:
{{- range $key, $value := .Values.cluster.postgresql.parameters }}
      {{ $key }}: {{ $value | quote }}
{{- end }}
  {{- with .Values.cluster.managed }}
  managed:
    {{- toYaml . | nindent 4 }}
  {{- end }}
