image:
  repository: ghcr.io/mednov-ai/playsay-registration-service
  tag: "registration-release-1.001.07-33"
  digest: "sha256:b72b368101e2b5967dae8c656489e29082c1f579f3bf3c0688a34d63254f834a"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: registration-release-1.001.07-33
  number: "33"
  branch: release/1.001.07
  branchLabel: registration-release-1.001.07
  commit: a171a7eda31f9faf8252cc5081a8435f3a12012e
  commitShort: "a171a7eda31f"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
registrationService:
  publicBaseUrl: https://online.honey.school
  keycloak:
    baseUrl: http://keycloak.keycloak.svc.cluster.local/keycloak
    realm: playsay
    studentTokenClientId: playsay-web
    existingSecret: playsay-registration
  emailService:
    baseUrl: http://email-service.playsay-prod.svc.cluster.local
    existingSecret: playsay-email
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=55 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 384Mi
