image:
  repository: ghcr.io/mednov-ai/playsay-registration-service
  tag: "registration-dev-21"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: registration-dev-21
  number: "21"
  branch: develop
  branchLabel: registration-dev
  commit: 0287acbfa7f6d502ebdedfc4b54391d280e2de75
  commitShort: "0287acbfa7f6"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
registrationService:
  publicBaseUrl: https://online.play-and-say.ru
  keycloak:
    baseUrl: http://keycloak.keycloak.svc.cluster.local/keycloak
    realm: playsay
    studentTokenClientId: playsay-web
    existingSecret: playsay-registration
  emailService:
    baseUrl: http://email-service.playsay-dev.svc.cluster.local
    existingSecret: playsay-email
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=55 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 384Mi
