image:
  repository: ghcr.io/mednov-ai/playsay-registration-service
  tag: "registration-release-01.004.05-45"
  digest: "sha256:38ee30c5f799480df11f829cfcc5feba747a4ce67512bd32c9009ed774c8f506"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: registration-release-01.004.05-45
  number: "45"
  branch: release/01.004.05
  branchLabel: registration-release-01.004.05
  commit: 711eea8d4740b9c0672cecd4be6b52f0e75ef597
  commitShort: "711eea8d4740"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
registrationService:
  publicBaseUrl: https://online.honey.school
  keycloak:
    baseUrl: http://keycloak.keycloak.svc.cluster.local/keycloak
    realm: playsay
    studentTokenClientId: playsay-web
    existingSecret: playsay-registration
  emailService:
    baseUrl: http://email-service.playsay-prod.svc.cluster.local
    existingSecret: playsay-email
runtime:
  javaToolOptions: "-Xms128m -Xmx256m -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 384Mi
  limits:
    cpu: 500m
    memory: 512Mi
