image:
  repository: ghcr.io/mednov-ai/playsay-registration-service
  tag: "registration-dev-35"
  digest: sha256:7c061417475b71f9c4e818318e8e833d4b43f82562b0ee909f12e72f271a23e0
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: registration-dev-35
  number: "35"
  branch: develop
  branchLabel: registration-dev
  commit: 587018326d28e009b78554a23edf237070502f7a
  commitShort: "587018326d28"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
registrationService:
  publicBaseUrl: https://dev.online.honey.school
  keycloak:
    baseUrl: http://keycloak.keycloak.svc.cluster.local/keycloak
    realm: playsay
    studentTokenClientId: playsay-web
    existingSecret: playsay-registration
  emailService:
    baseUrl: http://email-service.playsay-dev.svc.cluster.local
    existingSecret: playsay-email
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=55 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 384Mi
