image:
  repository: ghcr.io/mednov-ai/playsay-registration-service
  tag: "registration-hotfix-lesson-magic-links-58"
  digest: sha256:206e538637ac47994e769bf1eefef99a925331b4ae5d166cd98a5e61bd3ade55
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: registration-hotfix-lesson-magic-links-58
  number: "58"
  branch: hotfix/lesson-magic-links
  branchLabel: registration-hotfix-lesson-magic-links
  commit: 1bc2e68ac11cda4e69508eec17f03eedf77b6e60
  commitShort: "1bc2e68ac11c"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
registrationService:
  lessonAuth:
    issuer: https://dev.ops.honey.school/keycloak/realms/playsay
    allowedCallbackOrigins: https://dev.online.honey.school
  publicBaseUrl: https://dev.online.honey.school
  keycloak:
    baseUrl: http://keycloak.keycloak.svc.cluster.local/keycloak
    realm: playsay
    studentTokenClientId: playsay-web
    existingSecret: playsay-registration
  emailService:
    baseUrl: http://email-service.playsay-dev.svc.cluster.local
    existingSecret: playsay-email
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=55 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 384Mi
