image:
  repository: ghcr.io/mednov-ai/playsay-registration-service
  tag: "registration-release-1.001.06-4"
  digest: "sha256:5541902bfcc06d97649cc20707c0209691242eb02200004263edc039b3f5685f"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: registration-release-1.001.06-4
  number: "4"
  branch: release/1.001.06
  branchLabel: registration-release-1.001.06
  commit: 99b6432fa065cbc4976233166f8d5f2966706035
  commitShort: "99b6432fa065"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
registrationService:
  publicBaseUrl: https://online.honey.school
  keycloak:
    baseUrl: http://keycloak.keycloak.svc.cluster.local/keycloak
    realm: playsay
    studentTokenClientId: playsay-web
    existingSecret: playsay-registration
  emailService:
    baseUrl: http://email-service.playsay-prod.svc.cluster.local
    existingSecret: playsay-email
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=55 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 384Mi
