controller:
  jenkinsUrl: https://jenkins.honey.school/
  serviceType: NodePort
  nodePort: 32082
  servicePort: 8080
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - github
    - github-branch-source
    - credentials-binding
    - configuration-as-code
    - timestamper
    - pipeline-stage-view
    - generic-webhook-trigger
    - dark-theme
  overwritePlugins: true
  additionalExistingSecrets:
    - name: playsay-jenkins-credentials
      keyName: github-token
    - name: playsay-jenkins-credentials
      keyName: webhook-token
  JCasC:
    defaultConfig: true
    overwriteConfiguration: true
  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: 1500m
      memory: 2Gi

agent:
  containerCap: 1
  instanceCap: 1
  garbageCollection:
    enabled: true
    namespaces: jenkins
    timeout: 300
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi

persistence:
  enabled: true
  size: 16Gi

networkPolicy:
  enabled: false
