apiVersion: v1
kind: Service
metadata:
  name: {{ include "vocabulary-service.fullname" . }}
  labels: {{- include "vocabulary-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector: {{- include "vocabulary-service.selectorLabels" . | nindent 4 }}
