victoriaMetrics:
  httpPathPrefix: /victoria-metrics
  retentionPeriod: 3d
  service:
    type: NodePort
    nodePort: 32085
  storage:
    size: 5Gi

vmagent:
  scrapeInterval: 30s
  evaluationInterval: 30s

blackboxExporter:
  targets:
    - https://key.play-and-say.ru/
    - https://online.play-and-say.ru/
    - https://ops.play-and-say.ru:18443/victoria-metrics/vmui/
    - https://ops.play-and-say.ru:18443/argocd/
    - https://ops.play-and-say.ru:18443/jenkins/

alertmanager:
  telegram:
    enabled: true
    existingSecret: playsay-telegram-alerts
