victoriaMetrics:
  httpPathPrefix: /victoria-metrics
  retentionPeriod: 3d
  service:
    type: NodePort
    nodePort: 32085
  storage:
    size: 5Gi

victoriaLogs:
  enabled: true
  service:
    type: NodePort
    nodePort: 32089

vmagent:
  scrapeInterval: 30s
  evaluationInterval: 30s

blackboxExporter:
  targets:
    - https://dev.key.honey.school/
    - https://dev.online.honey.school/
    - https://dev.ops.honey.school/keycloak/realms/playsay/.well-known/openid-configuration

alertmanager:
  telegram:
    enabled: true
    existingSecret: playsay-telegram-alerts
