{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "livekit.fullname" . }}
  labels:
    {{- include "livekit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: signaling
      port: {{ .Values.service.port }}
      targetPort: signaling
      protocol: TCP
  selector:
    {{- include "livekit.selectorLabels" . | nindent 4 }}
{{- end }}
