image:
  repository: livekit/livekit-server
  tag: "v1.11.0"
imagePullSecrets: []
secret:
  existingName: livekit-keys
rtc:
  nodeIp: "146.103.126.15"
  udpPortRangeStart: 50000
  udpPortRangeEnd: 50020
