image:
  repository: livekit/livekit-server
  tag: "v1.11.0"
imagePullSecrets: []
secret:
  existingName: livekit-keys
rtc:
  interfaces:
    includes: [enp1s0]
  nodeIp: "65.109.55.110"
  tcpPort: 7882
  udpPortRangeStart: 51000
  udpPortRangeEnd: 51049
turn:
  enabled: true
  host: dev.online.honey.school
  port: 3479
webhook:
  enabled: true
  url: http://api-gateway.playsay-dev.svc.cluster.local/livekit/webhook
metrics:
  enabled: true
  port: 6789
