image:
  repository: ghcr.io/mednov-ai/playsay-email-service
  tag: "email-dev-14"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: email-dev-14
  number: "14"
  branch: develop
  branchLabel: email-dev
  commit: bccabf60ccbf30687afcd4dc31c6d27eb5ece4e8
  commitShort: "bccabf60ccbf"
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
service:
  type: ClusterIP
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
  hikariMaxPoolSize: "3"
emailService:
  existingSecret: playsay-email
  deliveryProvider: unisender-api
  fromName: Play&Say
  unisender:
    apiBaseUrl: https://goapi.unisender.ru/ru/transactional/api/v1
    userId: "8236338"
runtime:
  javaToolOptions: "-XX:InitialRAMPercentage=15 -XX:MaxRAMPercentage=45 -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=32m -XX:ActiveProcessorCount=1 -XX:+UseStringDeduplication -Djava.security.egd=file:/dev/urandom"
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 320Mi
