image:
  repository: ghcr.io/mednov-ai/playsay-api-gateway
  tag: "dev-32"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: dev-32
  number: "32"
  branch: develop
  branchLabel: dev
  commit: f55c49a93a261fa49bbe707c23cceffe2858bc48
  commitShort: "f55c49a93a26"
ingress:
  enabled: false
  host: api-gateway.dev.example.com
auth:
  issuerUri: https://ops.play-and-say.ru:18443/keycloak/realms/playsay
  jwkSetUri: http://keycloak.keycloak.svc.cluster.local/keycloak/realms/playsay/protocol/openid-connect/certs
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
