image:
  repository: ghcr.io/mednov-ai/playsay-api-gateway
  tag: "dev-18"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: dev-18
  number: "18"
  branch: develop
  branchLabel: dev
  commit: f2b7c689908360dae2789f02edb72a1a4c7b0a0a
  commitShort: f2b7c6899083
ingress:
  enabled: false
  host: api-gateway.dev.example.com
auth:
  issuerUri: https://ops.play-and-say.ru:18443/keycloak/realms/playsay
  jwkSetUri: http://keycloak.keycloak.svc.cluster.local/keycloak/realms/playsay/protocol/openid-connect/certs
