image:
  repository: ghcr.io/mednov-ai/playsay-api-gateway
  tag: "dev-67"
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: dev-67
  number: "67"
  branch: develop
  branchLabel: dev
  commit: da525e5004915170945c5461b2262eddad19c329
  commitShort: "da525e500491"
ingress:
  enabled: false
  host: api-gateway.dev.example.com
auth:
  issuerUri: https://ops.play-and-say.ru:18443/keycloak/realms/playsay
  jwkSetUri: http://keycloak.keycloak.svc.cluster.local/keycloak/realms/playsay/protocol/openid-connect/certs
ai:
  openai:
    enabled: true
    existingSecret: playsay-openai
    apiKeyKey: api-key
    modelKey: model
    baseUrl: https://api.openai.com/v1
database:
  existingSecret: playsay-app-db
  liquibaseEnabled: "false"
livekit:
  enabled: true
  serverUrl: wss://online.play-and-say.ru/livekit
  existingSecret: livekit-keys
  tokenTtlSeconds: "3600"
