apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://github.com/mednov-ai/playsay-infra.git
    targetRevision: release/01.004.03
    path: kustomize/cloudnative-pg-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
