apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collaboration-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mednov-ai/playsay-infra.git
    targetRevision: release/01.005.06
    path: helm-charts/collaboration-service
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: playsay-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
