apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-lite
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: https://github.com/mednov-ai/playsay-infra.git
    targetRevision: release/01.003.00
    path: helm-charts/monitoring-lite
    helm:
      releaseName: monitoring-lite
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
