apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - token-secret.yaml
  - argocd-rbac.yaml
  - workload-rbac.yaml
  - migration-runner.yaml
  - migration-admission.yaml
