apiVersion: v1
kind: Secret
metadata:
  name: playsay-ci-deployer-token
  namespace: playsay-ci-access
  annotations:
    kubernetes.io/service-account.name: playsay-ci-deployer
type: kubernetes.io/service-account-token
