theme:
  appBaseUrl: https://online.honey.school

image:
  repository: quay.io/keycloak/keycloak
  tag: "26.7.1"
  digest: sha256:f1f1f01e472c8a78df40d8f2a49a925274eda4d3d80d5f6edbb5c880ee3c01c6
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-pull-secret

build:
  name: upstream-26.7.1
  number: "0"
  branch: upstream
  branchLabel: upstream
  commit: upstream
  commitShort: upstream

global:
  security:
    allowInsecureImages: true

keycloak:
  replicaCount: 1
  hostname: https://ops.honey.school/keycloak
  httpRelativePath: /keycloak/
  service:
    nodePort: 32084
  adminSecret:
    name: keycloak-admin
    passwordKey: admin-password
  database:
    host: keycloak-postgresql
    port: 5432
    name: bitnami_keycloak
    username: bn_keycloak
    secretName: keycloak-postgresql
    passwordKey: password
  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: "2"
      memory: 1536Mi
  javaOpts: "-Xms512m -Xmx768m"
  themeCacheEnabled: true

postgresql:
  enabled: true
  architecture: standalone
  image:
    repository: bitnamilegacy/postgresql
  auth:
    username: bn_keycloak
    database: bitnami_keycloak
    existingSecret: keycloak-postgresql
    secretKeys:
      userPasswordKey: password
  primary:
    resourcesPreset: none
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 768Mi
    persistence:
      enabled: true
      size: 10Gi
