theme:
  appBaseUrl: https://dev.online.honey.school
  recoveryAllowedOrigins:
    - https://dev.online.honey.school
    - https://dev.online.honeyschool.ru
image:
  repository: ghcr.io/mednov-ai/playsay-keycloak
  tag: "keycloak-dev-12"
  digest: sha256:6ffb8662539101fa9e78dd6a186703116f02418e049fea7e70e9ca8c8b12d91d
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-pull-secret
build:
  name: keycloak-dev-12
  number: "12"
  branch: develop
  branchLabel: keycloak-dev
  commit: af467f645201c9abe7d501bafcfc8f8fa0ef3573
  commitShort: af467f645201
global:
  security:
    allowInsecureImages: true
keycloak:
  replicaCount: 1
  hostname: https://dev.ops.honey.school/keycloak
  httpRelativePath: /keycloak/
  service:
    nodePort: 32084
  adminSecret:
    name: keycloak-admin
    passwordKey: admin-password
  database:
    host: keycloak-postgresql
    port: 5432
    name: bitnami_keycloak
    username: bn_keycloak
    secretName: keycloak-postgresql
    passwordKey: password
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 750m
      memory: 900Mi
  javaOpts: "-Xms384m -Xmx600m"
  themeCacheEnabled: false
postgresql:
  enabled: true
  architecture: standalone
  image:
    repository: bitnamilegacy/postgresql
  auth:
    username: bn_keycloak
    database: bitnami_keycloak
    existingSecret: keycloak-postgresql
    secretKeys:
      userPasswordKey: password
  primary:
    resourcesPreset: none
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 384Mi
    persistence:
      enabled: true
      size: 4Gi
