keycloak:
  global:
    security:
      allowInsecureImages: true

  replicaCount: 1
  production: false
  httpEnabled: true
  httpRelativePath: /keycloak/
  proxyHeaders: xforwarded
  hostnameStrict: false

  image:
    repository: bitnamilegacy/keycloak

  auth:
    adminUser: admin
    existingSecret: keycloak-admin
    passwordSecretKey: admin-password

  cache:
    enabled: false

  service:
    type: NodePort
    ports:
      http: 80
    nodePorts:
      http: "32084"

  resourcesPreset: none
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 750m
      memory: 900Mi

  podAnnotations:
    checksum/playsay-theme: f5541d8a0f510dd42d53e724a9c363b4ee3d6b25d41b89ab995f4608dcc6bec9

  extraEnvVars:
    - name: KC_SPI_THEME_CACHE_THEMES
      value: "false"
    - name: KC_SPI_THEME_CACHE_TEMPLATES
      value: "false"
    - name: KC_SPI_THEME_STATIC_MAX_AGE
      value: "-1"

  extraVolumes:
    - name: playsay-theme
      configMap:
        name: keycloak-playsay-theme
        items:
          - key: theme.properties
            path: login/theme.properties
          - key: template.ftl
            path: login/template.ftl
          - key: messages_en.properties
            path: login/messages/messages_en.properties
          - key: messages_ru.properties
            path: login/messages/messages_ru.properties
          - key: messages_de.properties
            path: login/messages/messages_de.properties
          - key: messages_fr.properties
            path: login/messages/messages_fr.properties
          - key: playsay-login.css
            path: login/resources/css/playsay-login.css
          - key: logo.jpg
            path: login/resources/img/logo.jpg

  extraVolumeMounts:
    - name: playsay-theme
      mountPath: /opt/bitnami/keycloak/themes/playsay
      readOnly: true

  postgresql:
    enabled: true
    architecture: standalone
    image:
      repository: bitnamilegacy/postgresql
    auth:
      username: bn_keycloak
      database: bitnami_keycloak
      existingSecret: keycloak-postgresql
      secretKeys:
        userPasswordKey: password
    primary:
      resourcesPreset: none
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 384Mi
      persistence:
        enabled: true
        size: 4Gi
